### ISSUE TITLE
Receiving data after node deletion

### ISSUE THREAD

**Issue by kammala** [tipsi/aiozk#15]
If we have data watcher on some node, data changes will not be received after deleting and creating node again.

This behaviour can be reproduced with slightly changed test from `aiozk.test.test_watchers`
```python
@pytest.mark.asyncio
async def test_data_watch_delete(zk, path, data_watcher):
    data = []
    ready = asyncio.Event()
    test_data = b'test'

    async def data_callback(d):
        data.append(d)
        ready.set()

    await zk.set_data(path, test_data)

    data_watcher.add_callback(path, data_callback)
    await asyncio.sleep(0.2)
    assert data == [test_data]
    ready.clear()
    await zk.delete(path)

    await asyncio.wait_for(ready.wait(), timeout=1)
    assert ready.is_set()
    assert data == [test_data, NoNode]
    # data_watcher.remove_callback(path, data_callback)

    ready.clear()
    data = []
    await zk.create(path)
    await zk.set_data(path, test_data)
    await asyncio.sleep(0.2)
    assert data == [test_data]
    ready.clear()
```

Is this behaviour expected?
`kazoo`, for example, will received data in same situation.

**Comment by cybergrind** [comment]
@kammala until now I considered it as expected behavior: path was deleted - nothing to monitor and you must handle it yourself.
But since recipes can have quite high level logic over zk basics - maybe we can change this behavior to something that can fit requirements better.

So we have several options here:
1. add an option, like `survive_deletion`
  a. True by default - if it's desired behavior by default
  b. False by default - to support backward compatibility, but I belive it shouldn't break something important
2. add an option to handle node deletions/creation separately. in case you have some logic you rely on for these events and by default handle here deletion/creation.
3. add one more recipe with such support

If we do `1` - we also should consider this option for other recipes too.
In general I'm ok with 1 or 2. Maybe 2nd variant even better from point of extensibility/maintanability.

So @kammala 
* do you have anything to add?
* do you need and want to implement it yourself or maybe you want to wait when it will be implemented by me?

**Comment by kammala** [comment]
I think, that second option is preferable.

For example, we can add `on_delete_callback` to `DataWatcher`(or even `BaseWatcher`) and call it instead of calling `on_data_change_callback` with `aiozk.exc.NoNode` as data.
For API completeness we may add `on_create_callback` too, but I don't think that it would be very useful.

I'll try to provide pull request, but I don't know how quickly it will be ready

**Comment by cybergrind** [comment]
> I'll try to provide pull request, but I don't know how quickly it will be ready

Ok. Let me know if you need something
